# .goreleaser.yml
builds:
  # The Zig executable name (specified in build.zig)
  - binary: shamir
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    hooks:
      # This is called for every architecture.
      # eg: ./build.sh linux_amd64 csv2json
      post: ./.goreleaser/build.sh "{{ .Os }}" "{{ .Arch }}" "{{ .ProjectName }}" "{{ .Arm }}"
archives:
  - format: tar.gz
    # Additional static to bundle in the release.
    files:
      - README.md
      - LICENSE
